# Metadata shared across crates
[workspace.package]
version = "0.1.0"
license = "AGPL-3.0-or-later"

# Main crate
[package]
name = "libretube-sync"
version.workspace = true
edition = "2024"
description = "Server to sync user data (subscriptions, playlists, ...) between devices, written for LibreTube"
license.workspace = true

[dependencies]
# Web server and tests runtime
actix-rt = "2.11"
actix-web = "4.13"

# OpenAPI Docs
utoipa = { version = "5.4", features = ["actix_extras"] }
utoipa-actix-web = "0.1"
utoipa-scalar = { version = "0.3", features = ["actix-web"] }

# Database
diesel = { version = "2.3" }
diesel-async = { version = "0.8", features = [
  "async-connection-wrapper",
  "bb8",
  "migrations",
] }
diesel_migrations = { version = "2.3" }
uuid = { version = "1", features = ["serde", "v7"] }

# Logging
env_logger = "0.11.10"
log = "0.4"

# JSON
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

# Authentication
argon2 = { version = "0.5.3", features = ["std"] }
hmac = "0.13"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
sha2 = "0.11.0"
openidconnect = { version = "4.0", features = ["reqwest"] }
reqwest = "0.12"                                                  # version 0.12 is required by oauth2 crate used by openidconnect

# YouTube scraping
ytrss = { path = "ytrss" }

# Helper crates
config = { version = "0.15.22", default-features = false, features = [
  "convert-case",
  "toml",
] }
itertools = "0.14"
libsqlite3-sys = { version = "0.37.0", features = ["bundled"] }
thiserror = "2.0.18"
url = "2.5.8"

[features]
default = ["sqlite"]
# default = ["postgres"]
postgres = ["diesel-async/postgres"]
sqlite = ["diesel-async/sqlite", "diesel/returning_clauses_for_sqlite_3_35"]
