services:
  sync:
    container_name: libretube-sync
    image: ghcr.io/libre-tube/sync-server:main-postgres
    build:
      context: .
      args:
        - "DATABASE_BACKEND=postgres"
    environment:
      - "DATABASE_URL=postgres://postgres:password@db/libretube-sync"
      - "SECRET_KEY=changeme"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: libretube-sync-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=libretube-sync"
    volumes:
      - ./data:/var/lib/postgresql
    restart: unless-stopped
